services:
  smartlife-proxy:
    container_name: smartlife-proxy
    build:
      context: ./smartlife-proxy
      dockerfile: Dockerfile
    env_file:
      - ./smartlife-proxy/.env
    ports:
      - "8080:8080"
    restart: unless-stopped

  home-hub:
    container_name: projethome-hub
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    environment:
      SMARTLIFE_PROXY_BASE_URL: "http://smartlife-proxy:8080"
    ports:
      - "3000:3000"
    depends_on:
      - smartlife-proxy
    restart: unless-stopped
