services:
  smartlife-proxy:
    container_name: smartlife-proxy
    build:
      context: ./smartlife-proxy
      dockerfile: Dockerfile
    env_file:
      - ./smartlife-proxy/.env
    ports:
      - "8080:8080"
    restart: unless-stopped

  tablet-app:
    container_name: projethome-tablet
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      EXPO_PUBLIC_SMARTLIFE_PROXY_BASE_URL: "http://localhost:8080"
    ports:
      - "19006:19006"
      - "8081:8081"
      - "19000:19000"
    depends_on:
      - smartlife-proxy
    stdin_open: true
    tty: true
    restart: unless-stopped
